### ISSUE TITLE
Show the requested Word

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#1]
**As a User
I need to see the empty fields for the requested word 
So I know how long the word will be**

## Description

![UserStory1](https://user-images.githubusercontent.com/98757876/160380611-1efa0152-e2dc-43dc-8a2e-a1d257598188.svg)

## Acceptance Criteria

- [x] one empty field for every letter in the requested word is rendered 
(e.g. "Köln" -> four empty boxes are shown, for each letter in the word)
- [x] random word of a test-array is used 

## Tasks

- [x] creating Branch for User Story
- [x] creating component and adding logic
- [x] adding styled-components in storybook
- [x] testing responsiveness / accessibility
- [x] posting finished story in "code-reviews"
- [x] posting vercel-deployment of pull-request in "quality-assurance"
