### ISSUE TITLE
Start Screen

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#10]
## Value Preposition

**As a User
I want to have an start screen where i can choose different game categories
So I can decide with what kind of questions i want to play with**

## Description

![StartScreen](https://user-images.githubusercontent.com/98757876/161526423-60728da0-4a64-4e54-a7a2-adc189155ad1.png)![Categories](https://user-images.githubusercontent.com/98757876/164243892-e2470ef8-3f8f-44b3-8f29-610dcfb483d1.png)

## Acceptance Criteria

 - [x] index / "home" page is shown when loading the web-app
 - [x] "Starte ein Spiel" button leads to the game
 - [x] A list of categories is shown ( e.g. Towns, Countries, Animals etc.)
   - [x] Game starts if the user chooses a category 

## Tasks

- [x] creating Branch for User Story
- [x] creating component and adding logic
- [x] testing the logic of the components
- [x] adding styled-components
- [x] testing responsiveness / accessibility
- [x] posting finished story in "code-reviews"
- [x] posting vercel-deployment of pull-request in "quality-assurance"
