### ISSUE TITLE
End Game Button

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#11]
## Value Preposition

**As a User
I want an button to end the game
So I can return to the main menu**

## Description

Adding an Button to end the game

## Acceptance Criteria
 - [ ] when the "end game" button is clicked, an approval window will pop up and ask for permission to quit the game
 - [ ] index page is rendered

## Tasks

- [ ] creating Branch for User Story
- [ ] creating component and adding logic
- [ ] testing the logic of the components
- [ ] adding styled-components
- [ ] testing responsiveness / accessibility
- [ ] posting finished story in "code-reviews"
- [ ] posting vercel-deployment of pull-request in "quality-assurance"
