### ISSUE TITLE
Physical Keyboard

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#12]
## Value Preposition

**As a User
I want to be able to type the guessed letters on my physical keyboard
So I don’t have to click them on the screen, while playing on a computer**

## Description

The Player can press any letter on the keyboard to set it to "active" and submit the guess with the "return" key

## Acceptance Criteria
 - [x] the equivalent key on the screen is set to "active", when the physical key on the keyboard is pressed
 - [x] the logged in letter can be guessed with the use of the "return" key
 
## Tasks

- [x] creating Branch for User Story
- [x] creating component and adding logic
- [x] testing the logic of the components
- [x] adding styled-components
- [x] testing responsiveness / accessibility
- [x] posting finished story in "code-reviews"
- [x] posting vercel-deployment of pull-request in "quality-assurance"
