### ISSUE TITLE
Bot Player

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#13]
## Value Preposition

**As a User
I want an Bot to play against me
So I have to make better decisions while guessing, or the bot will steal all my time**

## Description

![BotPlayer](https://user-images.githubusercontent.com/98757876/161528675-e6ff6cfa-2f9d-40d4-bec0-e92edb543c0b.png)

## Acceptance Criteria

- [ ] if you are guessing a wrong letter, it will be greyed-out and it's the bots turn to guess
- [ ] if you are guessing a correct letter, it will be shown in green color and it's still your turn
        until all letters are guessed, or you made a wrong guess
- [ ] if the bot guesses a wrong letter, it will also be greyed-out and it's your turn again
- [ ] if the bot guesses a correct letter, it will be colored red, but it's your turn again, 
       because the bot is very efficient at guessing letters :D

## Tasks

- [ ] creating Branch for User Story
- [ ] creating component and adding logic
- [ ] testing the logic of the components
- [ ] adding styled-components
- [ ] testing responsiveness / accessibility
- [ ] posting finished story in "code-reviews"
- [ ] posting vercel-deployment of pull-request
