### ISSUE TITLE
Save Score

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#14]
## Value Preposition

**As a User 
I want the score to be saved when the time runs out, or I end the game
So I can see the scores in the future**

## Description

The score will be saved in the localStorage and a highscore button is available at the start screen

![Highscores](https://user-images.githubusercontent.com/98757876/161530193-5af00f26-8da7-4394-b1f5-36cd98afd72b.png)

## Acceptance Criteria
- [ ] as soon as the game ends (ending by time or user leaving the game), the current score and time will be saved in the local storage
- [ ] it will be shown at the "highscore" page

## Tasks

- [ ] creating Branch for User Story
- [ ] creating component and adding logic
- [ ] testing the logic of the components
- [ ] adding styled-components
- [ ] testing responsiveness / accessibility
- [ ] posting finished story in "code-reviews"
- [ ] posting vercel-deployment of pull-request in "quality-assurance"
