### ISSUE TITLE
Category Text

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#2]
**As a User
I want to see the category of the requested word
So i get a hint which kind of word is searched**

## Description

e.g. "Köln" -> The category "Stadt" is shown
![UserStory2](https://user-images.githubusercontent.com/98757876/160380762-16d4c512-c2da-4d61-a1fe-df0dbf61ef61.svg)

## Acceptance Criteria

- [x] the category / infoText of the random word is shown above the the empty fields and changes with the requested word

## Tasks

- [x] creating Branch for User Story
- [x] creating component and adding logic
- [x] adding styled-components
- [x] testing responsiveness / accessibility
- [x] posting finished story in "code-reviews"
- [x] posting vercel-deployment of pull-request in "quality-assurance"
