### ISSUE TITLE
Input fields

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#3]
## Value Preposition

**As a User
I need input-buttons so i can select a letter of the alphabet
To be able to guess the requested word**

## Description

![InputButtons](https://user-images.githubusercontent.com/98757876/161070492-ab50a12c-ec8e-480d-a069-758ce2f55507.png)

## Acceptance Criteria
- [x] an form with the alphabet of usable letters + submit button
  - [x] they can be selected and submitted as guess
  - [x] only one letter can be selected at any time
  - [x] they are colored green if in the word (true)
  - [x] the letter appears in the correct field of the requested word
  - [x] they are greyed-out/colored red if NOT in the word (false)
 
## Tasks

- [x] creating Branch for User Story
- [x] creating component and adding logic

- [x] testing the logic of the components: 
  - [x] checking if guessed letter is in requested word
   
- [x] adding styled-components
- [x] testing responsiveness / accessibility
- [x] posting finished story in "code-reviews"
- [x] posting vercel-deployment of pull-request in "quality-assurance"
