### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#4]
## Value Preposition

**As a User
I want an timer to count to zero, that can also add seconds to the clock, if a word is guessed correctly
So I have a limited amount of time for every word and have to be quick, before the game ends**

## Description

![Clock](https://user-images.githubusercontent.com/98757876/161521575-7b9f4953-cab2-4d1a-a208-280633eeaccb.png)![AddingTime](https://user-images.githubusercontent.com/98757876/161521589-d8b51529-a85a-4a34-a469-bb3ec20baa1e.png)

## Acceptance Criteria

- [x] the timer starts when the game is started
- [x] if the complete word is guessed, the timer adds some seconds to the clock, for every correct guessed letter
- [x] if the complete word is guessed, the timer reduces some seconds from the clock, for every wrong guessed letter
- [x] if the timer is zero, the game ends
- [x] a "neues Spiel" button appears, so you can start the next round

## Tasks

- [x] creating Branch for User Story
- [x] creating component and adding logic

- [x] testing the logic of the components:
  - [x] the game ends when the time is below 0 seconds
  - [x] a specific amount of seconds are added to the timer for each correct letter
 
- [x] adding styled-components
- [x] testing responsiveness / accessibility
- [x] posting finished story in "code-reviews"
- [x] posting vercel-deployment of pull-request in "quality-assurance"
