### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by flohip** [flohip/capstone-project#5]
## Value Preposition

**As a User
I want to see how many words i already guessed
So I can see what my score will be at the current moment**

## Description

![Score](https://user-images.githubusercontent.com/98757876/161521244-50024378-1dd0-452f-b323-b0e1d001819d.png)

## Acceptance Criteria
- [x] when a word is guessed correct, the score is raised by 1
- [x] the amount of correct guessed words is shown on a counter field

## Tasks

- [x] creating Branch for User Story
- [x] creating component and adding logic

- [x] testing the logic of the components:
  - [x] the score counter adds 1 when the word was guessed
 
- [x] adding styled-components
- [x] testing responsiveness / accessibility
- [x] posting finished story in "code-reviews"
- [x] posting vercel-deployment of pull-request in "quality-assurance"
